#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor amd gamma
bspc monitor -d 1 2 3 4 5 6 7 8
xgamma -gamma 0.8

# Rules window bspwm
bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^1'
bspc rule -a 'discord' desktop='^2' focus=off
bspc rule -a 'steam' desktop='^3' focus=off

# kill new run polybar
killall picom 2>/dev/null

# Custom command
sh ~/.fehbg &
$HOME/.config/polybar/launch.sh
setxkbmap -model pc105 -layout us,ru -option grp:alt_shift_toggle
numlockx
picom --vsync

export _JAVA_AWT_WM_NONREPARENTING=1
